CREATE TABLE `contactmanager`.`my_user` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(1000) NULL,
  `EMAIL` VARCHAR(255) NULL,
  `PASSWORD` VARCHAR(255) NULL,
  `ROLE` VARCHAR(255) NULL,
  `IS_ENABLED` TINYINT NULL,
  `IMAGE` VARCHAR(255) NULL,
  `ABOUT` VARCHAR(255) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE);